pull_request_rules:
  - name: automatic merge for Greenkeeper pull requests on master
    conditions:
      - author=greenkeeper[bot]
      - label~=greenkeeper
      - status-success~=Travis CI
      - status-success~=WIP
      - status-success~=netlify/relaxed-poincare-913bee/deploy-preview
    actions:
      merge:
        method: squash
        strict: true
  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author=dependabot[bot]
      - label~=dependencies
      - status-success~=Travis CI
      - status-success~=WIP
      - status-success~=netlify/relaxed-poincare-913bee/deploy-preview
    actions:
      merge:
        method: squash
        strict: true
  - name: automatic merge on CI success and review
    conditions:
      - label~=merge pull
      - status-success~=Travis CI
      - status-success~=WIP
    actions:
      merge:
        method: merge
        strict: true
  - name: delete merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}
