language: node_js
node_js:
  - 10

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm i -g firebase-tools
  - npm ci
  - npm run setup

script:
  - npm run lint

after_script:
  - npm i -g @adrianjost/report-viewer
  - rv-upload -F **/README.md
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > package/.npmrc
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master

cache:
  directories:
    - node_modules
    - backend/node_modules
    - frontend/node_modules
    - package/node_modules
